### ISSUE TITLE
./lsoracle: not found 

### ISSUE THREAD

**Issue by mayank-kabra2001** [lnis-uofu/LSOracle#82]
I am facing issues if I use optimize --strategy 1 on a blif file read as AIG network. 
![WhatsApp Image 2022-05-01 at 7 05 02 PM](https://user-images.githubusercontent.com/57330493/166148324-30b99032-4619-4dd8-a967-45450fa70c5f.jpeg)

Can you please help me out ? 
Thanks

**Comment by yashton** [comment]
You are attempting to call lsoracle in the current directory, but the the shell cannot find the file. Where is the lsoracle executable located?
