### ISSUE TITLE
Aborted (Core dumped) 

### ISSUE THREAD

**Issue by mayank-kabra2001** [lnis-uofu/LSOracle#83]
![Screenshot from 2022-05-02 16-25-04](https://user-images.githubusercontent.com/57330493/166224317-7e5a5c2f-b613-4321-9076-cc0a8a0bdfee.png)

Hi, I am facing following issue after using optimization -s 1.
Can someone help me out? 
Thanks

**Comment by NormandAlexandre** [comment]
Hey,
We have updated our commands and some are obsolete.
You can use : 
- “kahypar” for partitioning
- “optimize” for optimization 

“optimization” and “partitioning” are obsolete.
